restaurant_app/owner/urls.py
from django.conf.urls import url

from . import views

app_name = 'owner'

urlpatterns = [
	url(r'^(?P<own>[-\w]+)/$',views.principal,name = 'principal'),
        url(r'^(?P<own>[-\w]+)/peticiones/$',views.peticiones,name = 'peticiones'),
        url(r'^(?P<own>[-\w]+)/solicitud/(?P<pk>[0-9]+)/$',views.solicitudes,name = 'solicitudes'),
        url(r'^(?P<own>[-\w]+)/solicitud_fecha/$',views.solicitud_fecha,name='sol_fecha'),
]

restaurant_app/restaurant_app/urls.py
from django.conf.urls import include,url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include('users.urls')),
    url(r'^usuario/', include('sistema_de_reservas.urls')),
    url(r'^owner/', include('owner.urls')),
]

restaurant_app/owner/models.py
from django.db import models

# Create your models here.

restaurant_app/owner/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.template.response import TemplateResponse
from django.urls import reverse
from django.shortcuts import get_object_or_404, render
from django.template import loader
from django.utils import timezone
from users.models import usuario,owner
from sistema_de_reservas.models import Restaurantes, reservaciones
import time
# Create your views here.

def principal(request, own):
    latest_question_list = owner.objects.get(user = own)
    restaurante = Restaurantes.objects.get(pk = latest_question_list.restaurante)
    minimo= time.strftime("%Y-%m-%d")
    context = {
        'usuario': latest_question_list,
        'restaurante' : restaurante,
        'fecmin': minimo,
    }
    return render(request, 'owner/principal.html', context)
    #template = loader.get_template('owner/principal.html')
    #return HttpResponse(template.render(context,restaurante, request))

def peticiones(request, own):
    o = owner.objects.get(user = own)
    rest = Restaurantes.objects.get(pk = o.restaurante)
    peticiones = reservaciones.objects.filter(restaurantes = rest.nombre)
    output = peticiones.order_by('-dia')
    return render(request, 'owner/peticiones.html', {'peticion': output,'own':o})

def solicitudes(request,own,pk):
    o = owner.objects.get(user = own)
    peticiones = reservaciones.objects.get(pk=pk)
    return render(request, 'owner/peticion.html', {'peticion': peticiones,'own':o})

def solicitud_fecha(request,own):
    o = owner.objects.get(user = own)
    rest = Restaurantes.objects.get(pk = o.restaurante)
    peticiones = reservaciones.objects.filter(restaurantes = rest.nombre)
    fecha = request.POST.get("fecha","")
    minimo= time.strftime("%Y/%m/%d")
    output = peticiones.filter(dia = fecha).order_by('-hora')
    return render(request, 'owner/peticiones.html', {'peticion': output,'own':o})

restaurant_app/owner/templates/owner/peticion.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>solicitudes</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container-fluid">
  <h1>solicitud del restaurante {{peticion.restaurante}}</h1>
  <h2>pticion numero {{peticion.id}}</h2>
  <div class="row">
    <div class="col-sm-4" style="background-color:#84DCD7;">
    <li>Peticion del cliente </li>
	<li>Dia de la reserva: {{peticion.dia}}</li>
	<li>Hora: {{peticion.hora}}</li>
	<li>Cantidad de personas: {{peticion.cantidad_personas}}</li>
    </div>
    <div class="col-sm-8" style="background-color:lavenderblush;">
    <li>{{peticion.cliente}}</li>
    <li>{{peticion.dia}}</li>
    <li>{{peticion.hora}}</li>
    <li>{{peticion.cantidad_personas}}</li>
    </div>
  </div>
</div>
    
</body>
</html>

restaurant_app/owner/templates/owner/peticiones.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>solicitudes</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container">
  <h2>solicitudes</h2>
  <p>todas sus solicitudes</p>            
  <table class="table table-striped">
    <thead>
      <tr>
        <th>usuario</th>
        <th>fecha</th>
        <th>hora</th>
        <th>ver</th>
      </tr>
    </thead>
    <tbody>
    {% if  peticion %}
	{% for choice in peticion %}
      <tr>
        <td>{{choice.cliente}}</td>
        <td>{{choice.dia}}</td>
        <td>{{choice.hora}}</td>
        <td><a href ="/owner/{{own.user}}/solicitud/{{choice.id}}/">ver</td>
      </tr>
    {% endfor %}
	{% else %}
      <tr>
        <td>no hay solicitud</td>
        <td>no hay solicitud</td>
        <td>no hay solicitud</td>
        <td><a href ="/owner/{{own.user}}/">volver al inicio</td>
      </tr>
    </tbody>
    {% endif %}
  </table>
</div>

</body>
</html>

restaurant_app/owner/templates/owner/principal.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>{{restaurante.nombre}}</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container-fluid">
  <h1>restaurante {{restaurante.nombre}}</h1>
  <h2>usuario {{usuario.nombre}}</h2>
  <div class="row">
    <div class="col-sm-12" style="background-color:#84DCD7;">
    <li>opciones</li>
    </div>
    <div class="col-sm-12" style="background-color:lavenderblush;">
    <dl><a href="{%url 'owner:peticiones' usuario.user%}"> ver todas mis peticiones </a></dl>
    <form action="/owner/{{usuario.user}}/solicitud_fecha/" method="post">
	{% csrf_token %}
	<dl>Ver solicitude de la fecha:</dl>
	<dl><input type="date" name="fecha" min = {{fecmin}} value = {{fecmin}}></dl>
	<input type="submit" value="ver en esta fecha" class="btn btn-default">
	</form>
    </div>
  </div>
</div>
    
</body>
</html>