restaurant_app/owner/urls.py
from django.conf.urls import url

from . import views

app_name = 'owner'

urlpatterns = [
	url(r'^(?P<own>[-\w]+)/$',views.principal,name = 'principal'),
        url(r'^(?P<own>[-\w]+)/peticiones/$',views.peticiones,name = 'peticiones'),
        url(r'^(?P<own>[-\w]+)/solicitud/(?P<pk>[0-9]+)/$',views.solicitudes,name = 'solicitudes'),
        url(r'^(?P<own>[-\w]+)/solicitud_fecha/$',views.solicitud_fecha,name='sol_fecha'),
]

restaurant_app/restaurant_app/urls.py
from django.conf.urls import include,url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include('users.urls')),
    url(r'^usuario/', include('sistema_de_reservas.urls')),
    url(r'^owner/', include('owner.urls')),
]

restaurant_app/sistema_de_reservas/urls.py
from django.conf.urls import url

from . import views

app_name = 'reservas'

urlpatterns = [
    url(r'^restaurantes/(?P<user>[-\w]+)/$', views.index, name='restaurantes'),
    url(r'^sistema/(?P<user>[-\w]+)/(?P<pk>[0-9]+)/$', views.principal, name='sistema'),
    url(r'^(?P<pk>[0-9]+)/informacion/$', views.info_restaurante, name='informacion'),
    url(r'^mis_reservas/(?P<user>[-\w]+)/(?P<pk>[0-9]+)/$', views.mis_reservas, name='mis_reservas'),
    url(r'^reserva/(?P<user>[-\w]+)/(?P<pk>[0-9]+)/(?P<ident>[0-9]+)/$', views.reserva, name='reservas'),
    url(r'^delete/(?P<user>[-\w]+)/(?P<pk>[0-9]+)/(?P<ident>[0-9]+)/$', views.delete_reserva, name='borrar'),
    url(r'^hora_reserva/(?P<user>[-\w]+)/(?P<pk>[0-9]+)/$', views.hora_reserva, name='hora_reserva'),
    url(r'^dia_reserva/(?P<user>[-\w]+)/(?P<pk>[0-9]+)/$', views.dia_reserva, name='dia_reserva'),
    url(r'^final/(?P<ident>[0-9]+)/(?P<pk>[0-9]+)/$', views.final, name='final'),
    
]

restaurant_app/sistema_de_reservas/models.py
from django.db import models
from django.utils import timezone
from django.utils import timezone
import datetime

class Restaurantes(models.Model):
    nombre = models.CharField(max_length=20)
    descripcion = models.CharField(max_length=50)
    numero_tel = models.IntegerField()

    def __str__(self):
        return self.nombre
    
class reservaciones(models.Model):
    cliente = models.CharField(max_length=20)
    restaurantes = models.CharField(max_length=20)
    hora = models.CharField(max_length=20, default = "00:00")#aqui poner referencia a un modelo de calendario
    cantidad_personas = models.CharField(max_length=20)
    dia = models.DateField(default = timezone.now())

    def __str__(self):
        return self.cantidad_personas
    def __str__(self):
        return self.cliente
    def __str__(self):
        return self.dia

restaurant_app/sistema_de_reservas/views.py
from django.shortcuts import render
from django.http import HttpResponse
from users.models import usuario,owner
from sistema_de_reservas.models import Restaurantes,reservaciones
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.shortcuts import render_to_response
import datetime

# Create your views here.

def index(request, user):
    use = usuario.objects.get(user=user)
    restaurantes = Restaurantes.objects.all()
    context = {'restaurantes':restaurantes, 'usuario':use}
    return render(request,'sistemareservas/index.html',
                              context)
    
def principal(request,user,pk):
    use = usuario.objects.get(user=user)
    opciones = Restaurantes.objects.get(pk=pk)
    return render(request,'sistemareservas/principal.html',
                              {'opciones':opciones, 'usuario':use})

def info_restaurante(request,pk):
    informacion = Restaurantes.objects.get(pk=pk)
    return render(request,'sistemareservas/info_restaurante.html',
                              {'informacion':informacion})

def mis_reservas(request, user , pk):
    opciones = Restaurantes.objects.get(pk=pk)
    use = usuario.objects.get(user=user)
    reservas = reservaciones.objects.filter(cliente = use.user, restaurantes =opciones.nombre)
    rest = reservas.order_by('-dia','-hora')
    return render(request,'sistemareservas/mis_reservas.html',
                              {'opciones':opciones , 'reservas':rest})

def reserva(request, user, pk , ident):
    use = usuario.objects.get(user=user)
    rest=Restaurantes.objects.get(pk=pk)
    reservas = reservaciones.objects.get(pk=ident)
    context={'usuario':use,'restaurante':rest,'reserva':reservas}
    return render(request,'sistemareservas/reserva.html',
                              context)

def delete_reserva(request, user, pk , ident):
    use = usuario.objects.get(user=user)
    rest=Restaurantes.objects.get(pk=pk)
    reservas = reservaciones.objects.get(pk=ident)
    reservas.delete()
    return HttpResponseRedirect(reverse('reservas:restaurantes', kwargs={'user':use.user}))

def hora_reserva(request,user,pk):
    use = usuario.objects.get(user=user)
    rest=Restaurantes.objects.get(pk=pk)
    #D = reservaciones(cliente= use.user,
    #                  cantidad_personas= request.POST.get("cantidad",""),
    #                  dia =request.POST.get("fecha",""),
    #                  restaurantes=rest.nombre)
    #D.save()
    cliente= use.user
    cantidad_personas= request.POST.get("cantidad","")
    dia =request.POST.get("fecha","")
    restaurantes=rest.nombre
    confirmadas = reservaciones.objects.filter(cantidad_personas=cantidad_personas)
    return render(request,'sistemareservas/hora_reserva.html',
                              {'Confirmadas':confirmadas,'rest':rest,'usuario':use,'cliente':cliente,'cantidad_personas':cantidad_personas,'dia':dia,' restaurantes': restaurantes})

def dia_reserva(request,user,pk):
    ahora = datetime.datetime.now()
    Y=ahora.year
    m=ahora.month
    d=ahora.day
    if(d<10):
        if(m<10):
            minimo="%d-0%d-0%d"%(Y,m,d)
        else:
            minimo="%d-%d-0%d"%(Y,m,d)
    else:
        if(m<10):
            minimo="%d-0%d-%d"%(Y,m,d)
        else:
            minimo="%d-%d-%d"%(Y,m,d)
    if d>28:
        Md=28
    else:
        Md=d
    if d==12:
        Mm=1
        My=Y+1
    else:
        Mm=m+1
        My=Y
    if(d<10):
        if(m<10):
            Maximo="%d-0%d-0%d"%(My,Mm,Md)
        else:
            Maximo="%d-%d-0%d"%(My,Mm,Md)
    else:
        if(m<10):
            Maximo="%d-0%d-%d"%(My,Mm,Md)
        else:
            Maximo="%d-%d-%d"%(My,Mm,Md)
    use = usuario.objects.get(user=user)
    r=Restaurantes.objects.get(pk=pk)
    return render(request,'sistemareservas/dia_reserva.html',
                  {'rest':r, 'usuario':use,'fecmin':minimo,'fecmax':Maximo})

def final(request,ident,pk):
    r=usuario.objects.get(pk=pk)
    #reserva=reservaciones.objects.get(pk=ident)
    reserva=Restaurantes.objects.get(pk=ident)
    hora=request.POST.get("hora","")
    cantidad=request.POST.get("cantidad","")
    cliente=request.POST.get("cliente","")
    dia=request.POST.get("dia","")
    restaurantes=request.POST.get("restaurantes","")
    D = reservaciones(cliente= cliente,
                      cantidad_personas= cantidad,
                      dia =dia,
                      restaurantes=reserva.nombre,
                      hora=hora)
    D.save()
    return render(request,'sistemareservas/final.html',{'D':D,'rest':r})
    

restaurant_app/sistema_de_reservas/templates/sistema_de_reservas/dia_reserva.html
<html>
   <head>
      <title> Dia de reservaciones</title>
	</head>
	<body>
	Escoger dia y numero de personas<br/>
	<form action="{% url 'reservas:hora_reserva' rest.id %}" method="post">
{% csrf_token %}
Fecha: 
<input type="date" name="fecha" format="YYYY-MM-DD"><br>
Numero de personas
<select name="cantidad">
  <option value="1">1</option>
  <option value="2">2</option>
  <option value="3">3</option>
  <option value="4">4</option>
</select>
<input type="submit" value="Submit">



</form> 


	</body>
</html>

restaurant_app/sistema_de_reservas/templates/sistema_de_reservas/hora_reserva.html
<html>
   <head>
      <title>informacion de restaurante</title>
	</head>
	<body>
Escoja la hora:<br/>
	<form action="{% url 'reservas:hora_reserva' rest.id %}" method="post">
{% csrf_token %}
Horas: <br/>
<select name="hora">
  <option type="text" value="11:00am">11</option>
  <option type="text" value="1:00pm">1</option>
  <option type="text" value="3:00pm">3</option>
  <option type="text" value="7:00pm">7</option>
</select>
<input type="submit" value="Submit">
</form> 
<br/>
<br/>
Lista de reservaciones para la fecha seleccionada<br/>
	     {%for confirmadas in Confirmadas %}
		  {{confirmadas.id}}<br/>
		  {{confirmadas.cantidad_personas}}
		  {{confirmadas.dia}}<br/>
		  {{confirmadas.hora}}<br/>
		  {{confirmadas.restaurantes}}
{% endfor %}
	</body>
</html>

restaurant_app/sistema_de_reservas/templates/sistema_de_reservas/index.html
<html>
   <head>
      <title>Restaurantes</title>
	</head>
	<body>
	    {%for Restaurantes in restaurantes %}
		  <a href="{%url 'reservas:sistema' Restaurantes.id%}">{{Restaurantes.nombre}}</a><br/>
		  
{% endfor %}
	</body>
</html>

restaurant_app/sistema_de_reservas/templates/sistema_de_reservas/principal.html
<html>
   <head>
      <title>System</title>
	</head>
	<body>
	Sistema de reservaciones<br/>
	    <a href="{% url 'reservas:dia_reserva' opciones.id %}">Reservar</a><br/>
		<a href="{% url 'reservas:informacion' opciones.id %}">Informacion del restaurante</a><br/>
		<a href="{% url 'reservas:restaurantes'%}"">Mis reservaciones</a><br/>
	</body>
</html>