restaurant_app/owner/urls.py
from django.conf.urls import url

from . import views

app_name = 'owner'

urlpatterns = [
	url(r'^(?P<own>[-\w]+)/$',views.principal,name = 'principal'),
        url(r'^(?P<own>[-\w]+)/peticiones/$',views.peticiones,name = 'peticiones'),
        url(r'^(?P<own>[-\w]+)/solicitud/(?P<pk>[0-9]+)/$',views.solicitudes,name = 'solicitudes'),
        url(r'^(?P<own>[-\w]+)/solicitud_fecha/$',views.solicitud_fecha,name='sol_fecha'),
]

restaurant_app/restaurant_app/urls.py
from django.conf.urls import include,url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include('users.urls')),
    url(r'^usuario/', include('sistema_de_reservas.urls')),
    url(r'^owner/', include('owner.urls')),
]

restaurant_app/users/urls.py
from django.conf.urls import url

from . import views

app_name = 'users'

urlpatterns = [
    url(r'login/$',views.login,name= 'login'),
    url(r'ingresar/$',views.ingresar,name= 'ingresar'),
    url(r'registrar/$',views.registrar,name= 'registrar'),
    url(r'newU/$',views.newU,name= 'newU'),
    ]

restaurant_app/users/models.py
from django.db import models

# Create your models here.

class usuario(models.Model):
    nombre = models.CharField(max_length=20)
    user= models.CharField(max_length=20)
    contraseña = models.CharField(max_length=20)

class owner(models.Model):
    nombre = models.CharField(max_length=20)
    user= models.CharField(max_length=20)
    contraseña = models.CharField(max_length=20)
    restaurante = models.IntegerField(default=0) 

restaurant_app/users/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.template.response import TemplateResponse
from django.urls import reverse
from django.shortcuts import get_object_or_404, render
from django.template import loader
from django.utils import timezone
from .models import usuario,owner

# Create your views here.


def login(request):
    return render(request, 'users/login.html')

def registrar(request):
    return render(request, 'users/registrar.html',)

def newU(request):
    U= usuario(nombre= request.POST.get("nombre",""),user =request.POST.get("usuario",""),contraseña =request.POST.get("password",""))
    U.save()
    return render(request, 'users/login.html')
               
def ingresar(request):
    try:
        selected_choice = usuario.objects.get(nombre = request.POST.get("nombre",""))
    except (KeyError, usuario.DoesNotExist):
        try:
            selected_choice = usuario.objects.get(user = request.POST.get("usuario",""))
        except (KeyError, usuario.DoesNotExist):
            try:
                selected_choice = owner.objects.get(user = request.POST.get("usuario",""))
            except (KeyError, owner.DoesNotExist):
                return render(request, 'users/login.html', {
                    'error_message': "usuario no exite.",
                })
            else:
                return HttpResponseRedirect(reverse('owner:principal', args = (selected_choice.user,)))
        
        else:
            if(selected_choice.contraseña == request.POST.get("password","")):
                return HttpResponseRedirect(reverse('reservas:restaurantes', args = (selected_choice.user,)))
            else:
               return render(request, 'users/login.html', {
                'error_message': "contraseña incorrecta",
            })
    else:
        #return render(request, 'users/login.html', {'error_message': "usuario confirmado",})
        if(selected_choice.contraseña == request.POST.get("password","")):
            return HttpResponseRedirect(reverse('reservas:restaurantes', args = (selected_choice.user,)))
        else:
           return render(request, 'users/login.html', {
            'error_message': "contraseña incorrecta",
        })

restaurant_app/users/templates/users/login.html
<div class= "page-header">

{% load staticfiles %}
<title>login</title>
<head><h1>login</h1></head>
<link rel="stylesheet" type="text/css" href="{% static 'users/login.css' %}" />

</div>

<div class= "lateral">

<li> ingreso </li>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<li><a href="/users/registrar/" > inscribir nuevo usuario </a></li>

</div>

<div class="post">

<form action="{% url 'users:ingresar' %}" method="post">
{% csrf_token %}
<ul>nombre</ul>
<input type="text" name="nombre">
<ul>usuario</ul>
<input type="text" name="usuario">
<ul>password</ul>
<input type="password" name="password">
<ul></ul>
<bnt><input type="submit" value="Submit"></bnt>

</form>
</div>

<div class="caja1"></div>
<div class="caja2"></div>
<div class="caja3"></div>
<div class="caja4"></div>

restaurant_app/users/templates/users/registrar.html
<div class= "page-header">
{% load staticfiles %}
<title>Nuevo usuario</title>
<head><h3>registro de nuevo usuario</h3></head>
<link rel="stylesheet" type="text/css" href="{% static 'users/login.css' %}" />

</div>

<div class= "lateral">
<li><a href="/users/login/" > pagina de inicio </a></li>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
</div>

<div class="post">
<form action="{% url 'users:newU' %}" method="post">
{% csrf_token %}
<ul>nombre</ul>
<input type="text" name="nombre">
<ul>usuario</ul>
<input type="text" name="usuario">
<ul>password</ul>
<input type="text" name="password">
<ul></ul>
<input type="submit" value="Submit">
</form>
</div>

<div class="caja1"></div>
<div class="caja2"></div>
<div class="caja3"></div>
<div class="caja4"></div>